server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      enabled: false
      server:
        native:
          # 지원할 여러 경로 (도커 마운트 경로, 모듈 단위 실행 경로, 루트 실행 경로 등)
          search-locations: file:./config-repo,file:../config-repo,file:./backend/config-repo,file:/app/config-repo
