services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - msa-network

  config-service:
    build: ./config-service
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/app/config-repo
    networks:
      - msa-network

  user-service:
    build: ./user-service
    expose:
      - "3001"
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
    networks:
      - msa-network

  order-service:
    build: ./order-service
    expose:
      - "3002"
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
    networks:
      - msa-network

  api-gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
      - user-service
      - order-service
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
